<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD3aOCPB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD3aOCPB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerD3aOCPB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerD3aOCPB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerD3aOCPB\App_KernelDevDebugContainer([
    'container.build_hash' => 'D3aOCPB',
    'container.build_id' => 'ebbc3d9d',
    'container.build_time' => 1691477915,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerD3aOCPB');
